%% 焊缝属性
Seam_H = 5;  %焊缝高度cm
Seam_W = 10;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%% % - Generation @2 - % %%%%%%
% Seam_W = ones(5,1).*10;
% Seam_W_init = 10; %焊缝宽度cm
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
L_piece = 150; %焊缝长度cm
Num_interpor = 50; %单条焊缝插值数量
alpha = 45*pi/180;
LayerNUM = 5;%层数
SeamNum = [1 2 3 4 5];%焊缝数目每层
% %焊道数目修正
% for Fi = 2:5
%     SeamNum(Fi) = floor(3*(2*(Seam_H+(Fi-2)*Seam_H)/tan(alpha))/(2*Seam_W_init)+1);
% end
% %焊道宽度修正
% for Fi = 2:5
%     Seam_W(Fi) = 3*((2*Seam_H+(2*Fi-3)*Seam_H)/tan(alpha))/(4*floor(SeamNum(Fi))-1);
% end
%% 工件中心位置
Piece_Cx = 100;
Piece_Cy = 0;
Piece_Cz = 0;

%% 焊接过程安全点
Safe_Point = [Piece_Cx,Piece_Cy,Piece_Cz+0.3];
%% 1 LAYER Star-End Point Coordinate
P1s = [Piece_Cx,Piece_Cy+L_piece/2,Piece_Cz];
P1e = [Piece_Cx,Piece_Cy-L_piece/2,Piece_Cz];
layer1 = line_interp(P1s,P1e,Num_interpor);
%% 2 LAYER Star-End Point Coordinate
Lay_sn = 2; %表示这是第2层
layer2 = zeros(Num_interpor+1,3,SeamNum(Lay_sn));  % 51 x 3 x 2 的矩阵，2代表2条焊缝
P2se = zeros(2,3,SeamNum(Lay_sn));
for ij = 1:SeamNum(Lay_sn)
    P2se(1,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy+L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 起点 坐标
    P2se(2,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy-L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 终点 坐标
    layer2(:,:,ij) = line_interp(P2se(1,:,ij),P2se(2,:,ij),Num_interpor);
end
%% 3 LAYER Star-End Point Coordinate
Lay_sn = 3; %表示这是第3层
layer3 = zeros(Num_interpor+1,3,SeamNum(Lay_sn));  % 51 x 3 x 3 的矩阵
P3se = zeros(2,3,SeamNum(Lay_sn));
for ij = 1:SeamNum(Lay_sn)
    P3se(1,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy+L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 起点 坐标
    P3se(2,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy-L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 终点 坐标
    layer3(:,:,ij) = line_interp(P3se(1,:,ij),P3se(2,:,ij),Num_interpor);
end
%% 4 LAYER Star-End Point Coordinate
Lay_sn = 4; %表示这是第4层
layer4 = zeros(Num_interpor+1,3,SeamNum(Lay_sn));  % 51 x 3 x 4 的矩阵
P4se = zeros(2,3,SeamNum(Lay_sn));
for ij = 1:SeamNum(Lay_sn)
    P4se(1,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy+L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 起点 坐标
    P4se(2,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy-L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 终点 坐标
    layer4(:,:,ij) = line_interp(P4se(1,:,ij),P4se(2,:,ij),Num_interpor);
end
%% 5 LAYER Star-End Point Coordinate
Lay_sn = 5; %表示这是第5层
layer5 = zeros(Num_interpor+1,3,SeamNum(Lay_sn));  % 51 x 3 x 5 的矩阵
P5se = zeros(2,3,SeamNum(Lay_sn));
for ij = 1:SeamNum(Lay_sn)
    P5se(1,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy+L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 起点 坐标
    P5se(2,:,ij) = [Piece_Cx-(2*(Seam_H+(Lay_sn-2)*Seam_H)/tan(alpha))/2+(ij-1)*(2/3)*Seam_W, ...
                        Piece_Cy-L_piece/2, ...
                        Piece_Cz+Seam_H+(Lay_sn-2)*Seam_H];%第 Lay_sn 层，第 ij 道焊缝的 终点 坐标
    layer5(:,:,ij) = line_interp(P5se(1,:,ij),P5se(2,:,ij),Num_interpor);
end
order_welding = [];
Pos_MW = [Safe_Point;...
                Safe_Point;...
                layer1;...
                Safe_Point;...
                layer2(:,:,1);...
                Safe_Point;...
                layer2(:,:,2);...
                Safe_Point;...
                layer3(:,:,1);...
                Safe_Point;...
                layer3(:,:,3);...
                Safe_Point;...
                layer3(:,:,2);...
                Safe_Point;...
                layer4(:,:,1);...
                Safe_Point;...
                layer4(:,:,4);...
                Safe_Point;...
                layer4(:,:,2);...
                Safe_Point;...
                layer4(:,:,3);...
                Safe_Point;...
                layer5(:,:,1);...
                Safe_Point;...
                layer5(:,:,5);...
                Safe_Point;...
                layer5(:,:,2);...
                Safe_Point;...
                layer5(:,:,4);...
                Safe_Point;...
                layer5(:,:,3);...
                Safe_Point;];
Time_MW =1:21/length(Pos_MW):22-21/length(Pos_MW);
Time_MW=Time_MW';
save('MW_Traj.mat','Pos_MW','Time_MW');